---

- name: create ubuntu user password
  set_fact:
    pwd_ubuntu_user: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits,hexdigits') }}"

- name: output ubuntu user password
  debug:
    msg: '{{ pwd_ubuntu_user }}'

- user:
    name: ubuntu
    password: "{{ pwd_ubuntu_user | password_hash('sha512', 'LJH32sk2') }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- authorized_key:
    user: ubuntu
    key: '{{ item }}'
  with_items:
    - '{{ ssh_keys }}'
