---

- hosts: all
  user: root

  roles:
    - system


- hosts: dbserver
  user: root

  vars_files:
    - group_vars/main.yml

  roles:
    - mariadb


- hosts: webserver
  user: root

  vars_files:
    - group_vars/main.yml

  roles:
    - nginx


- hosts: appserver
  user: root

  vars_files:
    - group_vars/main.yml

  roles:
    - webapp
